name: Build nerplayerreleases APK

on:
  push:
    branches:
      - master
      - kugou
      - musicislandshare
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 拉取仓库代码及所有子模块
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      # 2. 配置 JDK 环境
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      # 3. 赋予 gradlew 执行权限
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 4. 执行 Gradle 构建 Release APK
      - name: Build Release APK
        run: ./gradlew assembleRelease --stacktrace

      # 5. 上传构建好的 Release APK 产物
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: NeriPlayer-${{ github.ref_name }}-release-apk
          path: app/build/outputs/apk/release/*.apk
